"use client";

import { useFinanceStore } from "@/lib/store";
import { useEffect } from "react";

/**
 * Notifications are generated by the user's own activity, not by anything
 * arriving from outside, so a fifteen-second poll spent a request every fifteen
 * seconds to learn nothing. Coming back to the app is the moment worth
 * checking; the interval is only a backstop for a session left open.
 */
const NOTIFICATION_POLL_INTERVAL = 300_000;

export function useNotificationSync() {
  const loadNotifications = useFinanceStore((state) => state.loadNotifications);

  useEffect(() => {
    let active = true;

    const refresh = () => {
      if (active && document.visibilityState === "visible") {
        void loadNotifications();
      }
    };
    const handleVisibility = () => refresh();

    refresh();
    const intervalId = window.setInterval(refresh, NOTIFICATION_POLL_INTERVAL);
    window.addEventListener("focus", refresh);
    document.addEventListener("visibilitychange", handleVisibility);

    return () => {
      active = false;
      window.clearInterval(intervalId);
      window.removeEventListener("focus", refresh);
      document.removeEventListener("visibilitychange", handleVisibility);
    };
  }, [loadNotifications]);
}
